namespace Dafny2Js.Emitters;

/// <summary>
/// Generates TypeScript adapter (dafny-bundle.ts) for Cloudflare Workers.
/// Similar to DenoEmitter but uses npm-style imports instead of esm.sh.
/// </summary>
public class CloudflareEmitter : SharedEmitter
{
  readonly string _cjsFilePath;
  readonly List<DispatchConfig> _dispatches;

  public CloudflareEmitter(
    List<DatatypeInfo> datatypes,
    List<FunctionInfo> functions,
    string domainModule,
    string appCoreModule,
    string cjsFileName,
    string cjsFilePath,
    List<DispatchConfig> dispatches,
    bool nullOptions = false)
    : base(datatypes, functions, domainModule, appCoreModule, cjsFileName, nullOptions)
  {
    _cjsFilePath = cjsFilePath;
    _dispatches = dispatches;
  }

  protected override bool EmitTypeScript => true;

  public override string Generate()
  {
    Sb.Clear();
    TypeMapper.EmitTypeScript = EmitTypeScript;

    var allTypesToGenerate = GetAllTypesToGenerate();

    // Collect all modules needed (including collaboration modules from dispatches)
    var allModules = allTypesToGenerate
      .Select(dt => dt.ModuleName)
      .Append(DomainModule)
      .Append(AppCoreModule)
      .Concat(_dispatches.Select(d => d.CollaborationModule))
      .Distinct()
      .ToList();

    // 1. Header and imports
    EmitHeader();
    Sb.AppendLine();

    // 2. Dafny runtime setup
    EmitDafnyRuntimeSetup(allModules);
    Sb.AppendLine();

    // 3. Helpers
    EmitHelpers(allTypesToGenerate);
    Sb.AppendLine();

    // 4. TypeScript interfaces
    EmitTypeScriptInterfaces(allTypesToGenerate);

    // 5. Null-option preprocessing (if enabled)
    if (NullOptions)
    {
      EmitNullOptionPreprocessing();
      Sb.AppendLine();
    }

    // 6. Datatype conversions
    EmitDatatypeConversions(allTypesToGenerate);

    // 7. Export converters and modules
    EmitExports(allModules, allTypesToGenerate);
    Sb.AppendLine();

    // 8. Init function (from Domain.Init())
    EmitInitFunction();

    // 9. ServerState conversions (if we have dispatches)
    if (_dispatches.Count > 0)
    {
      EmitServerStateConversions(_dispatches[0].CollaborationModule);
    }

    // 10. Dispatch functions
    foreach (var dispatch in _dispatches)
    {
      EmitDispatchFunction(dispatch);
      Sb.AppendLine();
    }

    return Sb.ToString();
  }

  void EmitHeader()
  {
    // TODO: Fix emitter to generate proper TypeScript types instead of @ts-nocheck
    Sb.AppendLine("// @ts-nocheck");
    Sb.AppendLine("// Generated by dafny2js --cloudflare");
    Sb.AppendLine("// DO NOT EDIT - regenerate with: ./compile.sh");
    Sb.AppendLine();
    Sb.AppendLine("// Note: Unlike Deno, Cloudflare Workers don't support new Function().");
    Sb.AppendLine("// The Dafny code is included directly in this bundle.");
  }

  void EmitDafnyRuntimeSetup(List<string> moduleNames)
  {
    // Read the .cjs file and transform it for Cloudflare
    var dafnyCode = File.ReadAllText(_cjsFilePath);

    // Remove the require('bignumber.js') line since we import it as ESM
    // Replace: const BigNumber = require('bignumber.js');
    // With our own import at the top
    dafnyCode = System.Text.RegularExpressions.Regex.Replace(
      dafnyCode,
      @"const BigNumber = require\(['""]bignumber\.js['""]\);",
      "// BigNumber imported as ESM above"
    );

    var modules = string.Join(", ", moduleNames);

    Sb.AppendLine();
    Sb.AppendLine("// Import BigNumber as ESM (Wrangler will bundle it)");
    Sb.AppendLine("import BigNumber from 'bignumber.js';");
    Sb.AppendLine();
    Sb.AppendLine("// Configure BigNumber");
    Sb.AppendLine("BigNumber.config({ MODULO_MODE: BigNumber.EUCLID });");
    Sb.AppendLine();
    Sb.AppendLine("// ============================================================================");
    Sb.AppendLine("// Dafny Compiled Code (included directly, no eval)");
    Sb.AppendLine("// ============================================================================");
    Sb.AppendLine();

    // Include the Dafny code directly
    // The code defines: _dafny, TodoDomain, TodoMultiCollaboration, etc. as let variables
    Sb.AppendLine(dafnyCode);
    Sb.AppendLine();
  }

  void EmitNullOptionPreprocessing()
  {
    Sb.AppendLine("// ============================================================================");
    Sb.AppendLine("// Null-Option Preprocessing (for DB compatibility)");
    Sb.AppendLine("// ============================================================================");
    Sb.AppendLine();
    Sb.AppendLine("// Convert null to { type: 'None' } for Option fields");
    Sb.AppendLine("// eslint-disable-next-line @typescript-eslint/no-explicit-any");
    Sb.AppendLine("const fixOption = (val: any): any => {");
    Sb.AppendLine("  if (val === null || val === undefined) return { type: 'None' };");
    Sb.AppendLine("  if (val && val.type) return val;");
    Sb.AppendLine("  return { type: 'Some', value: val };");
    Sb.AppendLine("};");
    Sb.AppendLine();

    // Handle tagged option format from client
    Sb.AppendLine("// Handle tagged option format from client: { type: 'Some', value: ... } or { type: 'None' }");
    Sb.AppendLine("// eslint-disable-next-line @typescript-eslint/no-explicit-any");
    Sb.AppendLine("const taggedOptionToValue = (val: any, converter: (x: any) => any = (x) => x): any => {");
    Sb.AppendLine("  if (val === null || val === undefined) {");
    Sb.AppendLine($"    return {DomainModule}.Option.create_None();");
    Sb.AppendLine("  }");
    Sb.AppendLine("  if (val.type === 'None') {");
    Sb.AppendLine($"    return {DomainModule}.Option.create_None();");
    Sb.AppendLine("  }");
    Sb.AppendLine("  if (val.type === 'Some') {");
    Sb.AppendLine($"    return {DomainModule}.Option.create_Some(converter(val.value));");
    Sb.AppendLine("  }");
    Sb.AppendLine("  // Fallback: treat as raw value");
    Sb.AppendLine($"  return {DomainModule}.Option.create_Some(converter(val));");
    Sb.AppendLine("};");
    Sb.AppendLine();

    // Option to JS (null-based)
    Sb.AppendLine("// Convert Dafny Option to null-based JS");
    Sb.AppendLine("// eslint-disable-next-line @typescript-eslint/no-explicit-any");
    Sb.AppendLine("const optionToJs = (opt: any, converter: (x: any) => any = (x) => x): any => {");
    Sb.AppendLine("  if (opt.is_None) return null;");
    Sb.AppendLine("  return converter(opt.dtor_value);");
    Sb.AppendLine("};");
    Sb.AppendLine();
  }

  void EmitExports(List<string> allModules, List<DatatypeInfo> allTypesToGenerate)
  {
    Sb.AppendLine("// ============================================================================");
    Sb.AppendLine("// Exports");
    Sb.AppendLine("// ============================================================================");
    Sb.AppendLine();

    // Export modules
    var modulesStr = string.Join(", ", allModules);
    Sb.AppendLine($"export {{ _dafny, {modulesStr}, BigNumber }};");
    Sb.AppendLine();

    // Export converters
    var exportedNames = new HashSet<string>();
    foreach (var dt in allTypesToGenerate)
    {
      var lower = TypeMapper.SanitizeForJs(dt.Name).ToLowerInvariant();
      if (!exportedNames.Add(lower)) continue;
    }

    if (exportedNames.Count > 0)
    {
      var converterExports = exportedNames
        .SelectMany(n => new[] { $"{n}FromJson", $"{n}ToJson" });
      Sb.AppendLine($"export {{ {string.Join(", ", converterExports)} }};");
    }

    Sb.AppendLine();
    var helperExports = new[] { "dafnyStringToJs", "seqToArray", "toNumber" }
      .Where(h => NeededSymbols.Contains(h))
      .ToList();
    if (helperExports.Count > 0)
      Sb.AppendLine($"export {{ {string.Join(", ", helperExports)} }};");
  }

  void EmitInitFunction()
  {
    Sb.AppendLine("// ============================================================================");
    Sb.AppendLine("// init() - Get initial domain state from Dafny");
    Sb.AppendLine("// ============================================================================");
    Sb.AppendLine();
    Sb.AppendLine("/**");
    Sb.AppendLine($" * Returns the initial state from {DomainModule}.Init()");
    Sb.AppendLine(" * Use this instead of hardcoding initial state in your worker.");
    Sb.AppendLine(" */");
    Sb.AppendLine("export function init(): any {");
    Sb.AppendLine($"  const dafnyModel = {DomainModule}.__default.Init();");
    Sb.AppendLine("  return modelToJson(dafnyModel);");
    Sb.AppendLine("}");
    Sb.AppendLine();
  }

  void EmitDispatchFunction(DispatchConfig config)
  {
    Sb.AppendLine("// ============================================================================");
    Sb.AppendLine($"// {config.Name} - Verified Dispatch Function");
    Sb.AppendLine("// ============================================================================");
    Sb.AppendLine();

    // TypeScript interfaces
    EmitDispatchInterfaces(config);

    // The dispatch function itself
    Sb.AppendLine($"export function {config.Name}(");
    Sb.AppendLine("  stateJson: any,");
    Sb.AppendLine("  appliedLog: any[],");
    Sb.AppendLine("  baseVersion: number,");
    Sb.AppendLine("  actionJson: any,");
    Sb.AppendLine("  auditLog?: any[]");
    Sb.AppendLine("): DispatchResult {");

    // Build ServerState from JSON
    Sb.AppendLine("  // Build ServerState from JSON");
    Sb.AppendLine("  const serverState = serverStateFromJson({");
    Sb.AppendLine("    present: stateJson,");
    Sb.AppendLine("    appliedLog: appliedLog,");
    Sb.AppendLine("    auditLog: auditLog || []");
    Sb.AppendLine("  });");
    Sb.AppendLine();

    // Call verified Dispatch
    Sb.AppendLine("  // Call VERIFIED Dispatch");
    Sb.AppendLine("  const action = actionFromJson(actionJson);");
    Sb.AppendLine($"  const result = {config.CollaborationModule}.__default.Dispatch(");
    Sb.AppendLine("    serverState,");
    Sb.AppendLine("    new BigNumber(baseVersion),");
    Sb.AppendLine("    action");
    Sb.AppendLine("  );");
    Sb.AppendLine();

    // Extract result (tuple: [newServerState, reply])
    Sb.AppendLine("  // Result is a tuple: [newServerState, reply]");
    Sb.AppendLine("  const newServerState = result[0];");
    Sb.AppendLine("  const reply = result[1];");
    Sb.AppendLine();

    // Convert result
    Sb.AppendLine("  // Extract new state");
    Sb.AppendLine("  const newStateJson = serverStateToJson(newServerState);");
    Sb.AppendLine();

    // Handle reply type
    Sb.AppendLine("  // Check reply type");
    Sb.AppendLine("  if (reply.is_Accepted) {");
    Sb.AppendLine("    return {");
    Sb.AppendLine("      status: 'accepted',");
    Sb.AppendLine("      state: newStateJson.present,");
    Sb.AppendLine("      newVersion: toNumber(reply.dtor_newVersion),");
    Sb.AppendLine("      appliedAction: actionToJson(reply.dtor_applied),");
    Sb.AppendLine("      noChange: reply.dtor_noChange,");
    Sb.AppendLine("      appliedLog: newStateJson.appliedLog,");
    Sb.AppendLine("      auditLog: newStateJson.auditLog");
    Sb.AppendLine("    };");
    Sb.AppendLine("  } else {");
    Sb.AppendLine("    // Rejected");
    Sb.AppendLine("    return {");
    Sb.AppendLine("      status: 'rejected',");
    Sb.AppendLine("      reason: 'DomainInvalid',");
    Sb.AppendLine("      appliedAction: actionToJson(reply.dtor_rebased)");
    Sb.AppendLine("    };");
    Sb.AppendLine("  }");
    Sb.AppendLine("}");
  }

  void EmitDispatchInterfaces(DispatchConfig config)
  {
    Sb.AppendLine("export interface DispatchResult {");
    Sb.AppendLine("  status: 'accepted' | 'rejected';");
    Sb.AppendLine("  state?: any;");
    Sb.AppendLine("  appliedAction?: any;");
    Sb.AppendLine("  newVersion?: number;");
    Sb.AppendLine("  noChange?: boolean;");
    Sb.AppendLine("  appliedLog?: any[];");
    Sb.AppendLine("  auditLog?: any[];");
    Sb.AppendLine("  reason?: string;");
    Sb.AppendLine("}");
    Sb.AppendLine();
  }

  /// <summary>
  /// Emit ServerState conversion functions needed for dispatch.
  /// This should be called after datatype conversions.
  /// </summary>
  public void EmitServerStateConversions(string collaborationModule)
  {
    Sb.AppendLine("// ============================================================================");
    Sb.AppendLine("// ServerState Conversions (for verified Dispatch)");
    Sb.AppendLine("// ============================================================================");
    Sb.AppendLine();

    // serverStateFromJson
    Sb.AppendLine("// eslint-disable-next-line @typescript-eslint/no-explicit-any");
    Sb.AppendLine("const serverStateFromJson = (json: any): any => {");
    Sb.AppendLine("  const present = modelFromJson(json.present);");
    Sb.AppendLine();
    Sb.AppendLine("  // Convert appliedLog: Action[] -> Dafny seq<Action>");
    Sb.AppendLine("  const appliedActions = (json.appliedLog || []).map(actionFromJson);");
    Sb.AppendLine("  const appliedLog = _dafny.Seq.of(...appliedActions);");
    Sb.AppendLine();
    Sb.AppendLine("  // Convert auditLog: AuditRecord[] -> Dafny seq<RequestRecord>");
    Sb.AppendLine("  const auditRecords = (json.auditLog || []).map((rec: any) => {");
    Sb.AppendLine("    const outcome = rec.outcome.type === 'accepted'");
    Sb.AppendLine($"      ? {collaborationModule}.RequestOutcome.create_AuditAccepted(");
    Sb.AppendLine("          actionFromJson(rec.outcome.applied),");
    Sb.AppendLine("          rec.outcome.noChange || false");
    Sb.AppendLine("        )");
    Sb.AppendLine($"      : {collaborationModule}.RequestOutcome.create_AuditRejected(");
    Sb.AppendLine($"          {collaborationModule}.RejectReason.create_DomainInvalid(),");
    Sb.AppendLine("          actionFromJson(rec.outcome.applied || rec.rebased)");
    Sb.AppendLine("        );");
    Sb.AppendLine();
    Sb.AppendLine($"    return {collaborationModule}.RequestRecord.create_Req(");
    Sb.AppendLine("      new BigNumber(rec.baseVersion),");
    Sb.AppendLine("      actionFromJson(rec.orig),");
    Sb.AppendLine("      actionFromJson(rec.rebased),");
    Sb.AppendLine("      actionFromJson(rec.chosen),");
    Sb.AppendLine("      outcome");
    Sb.AppendLine("    );");
    Sb.AppendLine("  });");
    Sb.AppendLine("  const auditLog = _dafny.Seq.of(...auditRecords);");
    Sb.AppendLine();
    Sb.AppendLine($"  return {collaborationModule}.ServerState.create_ServerState(");
    Sb.AppendLine("    present,");
    Sb.AppendLine("    appliedLog,");
    Sb.AppendLine("    auditLog");
    Sb.AppendLine("  );");
    Sb.AppendLine("};");
    Sb.AppendLine();

    // serverStateToJson
    Sb.AppendLine("// eslint-disable-next-line @typescript-eslint/no-explicit-any");
    Sb.AppendLine("const serverStateToJson = (s: any): any => {");
    Sb.AppendLine("  const present = modelToJson(s.dtor_present);");
    Sb.AppendLine();
    Sb.AppendLine("  // Convert appliedLog: Dafny seq<Action> -> Action[]");
    Sb.AppendLine("  const appliedLog = seqToArray(s.dtor_appliedLog).map(actionToJson);");
    Sb.AppendLine();
    Sb.AppendLine("  // Convert auditLog: Dafny seq<RequestRecord> -> AuditRecord[]");
    Sb.AppendLine("  const auditLog = seqToArray(s.dtor_auditLog).map((rec: any) => {");
    Sb.AppendLine("    const outcome = rec.dtor_outcome;");
    Sb.AppendLine("    return {");
    Sb.AppendLine("      baseVersion: toNumber(rec.dtor_baseVersion),");
    Sb.AppendLine("      orig: actionToJson(rec.dtor_orig),");
    Sb.AppendLine("      rebased: actionToJson(rec.dtor_rebased),");
    Sb.AppendLine("      chosen: actionToJson(rec.dtor_chosen),");
    Sb.AppendLine("      outcome: outcome.is_AuditAccepted");
    Sb.AppendLine("        ? {");
    Sb.AppendLine("            type: 'accepted' as const,");
    Sb.AppendLine("            applied: actionToJson(outcome.dtor_applied),");
    Sb.AppendLine("            noChange: outcome.dtor_noChange");
    Sb.AppendLine("          }");
    Sb.AppendLine("        : {");
    Sb.AppendLine("            type: 'rejected' as const,");
    Sb.AppendLine("            reason: 'DomainInvalid',");
    Sb.AppendLine("            applied: actionToJson(outcome.dtor_rebased)");
    Sb.AppendLine("          }");
    Sb.AppendLine("    };");
    Sb.AppendLine("  });");
    Sb.AppendLine();
    Sb.AppendLine("  return { present, appliedLog, auditLog };");
    Sb.AppendLine("};");
    Sb.AppendLine();
  }
}
