namespace Dafny2Js.Emitters;

/// <summary>
/// Generates a universal TypeScript wrapper that inlines the .cjs code as a template literal.
/// Works in any JS runtime (Node, browser, Turbopack, Vite, webpack) with no bundler-specific imports.
/// </summary>
public class InlineEmitter : ClientEmitter
{
  readonly string _cjsFilePath;

  public InlineEmitter(
    List<DatatypeInfo> datatypes,
    List<FunctionInfo> functions,
    string domainModule,
    string appCoreModule,
    string cjsFileName,
    string cjsFilePath,
    bool nullOptions = false,
    bool jsonApi = false)
    : base(datatypes, functions, domainModule, appCoreModule, cjsFileName, nullOptions, useTypeScript: true, jsonApi)
  {
    _cjsFilePath = cjsFilePath;
  }

  protected override void EmitBoilerplate(List<string> moduleNames)
  {
    var modules = string.Join(", ", moduleNames);
    var dafnyCode = File.ReadAllText(_cjsFilePath);
    var escapedCode = EscapeForTemplateLiteral(dafnyCode);

    Sb.AppendLine("// Generated by dafny2js (inline target)");
    Sb.AppendLine("// Do not edit manually - regenerate from Dafny sources");
    Sb.AppendLine();
    Sb.AppendLine("import BigNumber from 'bignumber.js';");
    Sb.AppendLine();
    Sb.AppendLine("// Configure BigNumber as Dafny expects");
    Sb.AppendLine("BigNumber.config({ MODULO_MODE: BigNumber.EUCLID });");
    Sb.AppendLine();
    Sb.AppendLine("// Set up the environment and evaluate the Dafny code");
    Sb.AppendLine("const require = (mod: string) => {");
    Sb.AppendLine("  if (mod === 'bignumber.js') return BigNumber;");
    Sb.AppendLine("  throw new Error(`Unknown module: ${mod}`);");
    Sb.AppendLine("};");
    Sb.AppendLine();
    Sb.AppendLine("// Dafny code inlined as template literal (no runtime file reading or bundler imports)");
    Sb.AppendLine("const initDafny = new Function('require', `");
    Sb.AppendLine(escapedCode);
    Sb.AppendLine($"  return {{ _dafny, {modules} }};");
    Sb.AppendLine("`);");
    Sb.AppendLine();
    Sb.AppendLine($"const {{ _dafny, {modules} }} = initDafny(require);");
  }
}
