namespace Dafny2Js.Emitters;

/// <summary>
/// Generates a Node-compatible TypeScript wrapper.
/// Identical to ClientEmitter but loads the .cjs via fs.readFileSync instead of Vite's ?raw import.
/// </summary>
public class NodeEmitter : ClientEmitter
{
  public NodeEmitter(
    List<DatatypeInfo> datatypes,
    List<FunctionInfo> functions,
    string domainModule,
    string appCoreModule,
    string cjsFileName,
    bool nullOptions = false,
    bool jsonApi = false)
    : base(datatypes, functions, domainModule, appCoreModule, cjsFileName, nullOptions, useTypeScript: true, jsonApi)
  {
  }

  protected override void EmitBoilerplate(List<string> moduleNames)
  {
    var modules = string.Join(", ", moduleNames);

    Sb.AppendLine("// Generated by dafny2js (node target)");
    Sb.AppendLine("// Do not edit manually - regenerate from Dafny sources");
    Sb.AppendLine();
    Sb.AppendLine("import BigNumber from 'bignumber.js';");
    Sb.AppendLine("import fs from 'node:fs';");
    Sb.AppendLine("import path from 'node:path';");
    Sb.AppendLine("import { fileURLToPath } from 'node:url';");
    Sb.AppendLine();
    Sb.AppendLine("// Configure BigNumber as Dafny expects");
    Sb.AppendLine("BigNumber.config({ MODULO_MODE: BigNumber.EUCLID });");
    Sb.AppendLine();
    Sb.AppendLine("// Load the compiled Dafny code from disk");
    Sb.AppendLine("const __filename = fileURLToPath(import.meta.url);");
    Sb.AppendLine("const __dirname = path.dirname(__filename);");
    Sb.AppendLine($"const dafnyCode = fs.readFileSync(path.resolve(__dirname, './{CjsFileName}'), 'utf-8');");
    Sb.AppendLine();
    Sb.AppendLine("// Set up the environment and evaluate the Dafny code");
    Sb.AppendLine("const require = (mod: string) => {");
    Sb.AppendLine("  if (mod === 'bignumber.js') return BigNumber;");
    Sb.AppendLine("  throw new Error(`Unknown module: ${mod}`);");
    Sb.AppendLine("};");
    Sb.AppendLine();
    Sb.AppendLine("// Create a function that evaluates the code with proper scope");
    Sb.AppendLine("const initDafny = new Function('require', `");
    Sb.AppendLine("  ${dafnyCode}");
    Sb.AppendLine($"  return {{ _dafny, {modules} }};");
    Sb.AppendLine("`);");
    Sb.AppendLine();
    Sb.AppendLine($"const {{ _dafny, {modules} }} = initDafny(require);");
  }
}
